name: Check Unbound config
on: push
jobs:
  unbound:
    name: Check Unbound config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Unbound
        run: sudo apt-get update && sudo apt-get install -y unbound
      - name: Check unbound config
        run: unbound-checkconf unbound/unbound.conf
